// A Vite plugin that writes dist/build.json: what this build was made from.
//
// It exists because the built front end is committed. A committed build artefact rots
// silently — someone edits an .vue file, forgets `make ui`, and the binary keeps serving
// last week's bundle with no error anywhere. So the build records a hash of its own
// sources, and a Go test (`TestBuiltUIMatchesItsSources`) recomputes it. Same trick as
// the committed diagrams, whose SVG carries `mmd-sha256` for the same reason.
//
// The hash covers every file the bundle is built from — src/**, index.html, the config,
// and the dependency lockfile — because a dependency bump changes the output too.
import { createHash } from 'node:crypto'
import { readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs'
import { join, relative } from 'node:path'

const SKIP = new Set(['node_modules', 'dist', '.git'])

function walk(dir, out = []) {
  for (const name of readdirSync(dir).sort()) {
    if (SKIP.has(name))
      continue
    const path = join(dir, name)
    if (statSync(path).isDirectory())
      walk(path, out)
    else out.push(path)
  }
  return out
}

// Not exported: the only other place that needs this definition is Go, and
// `uiSourceHash` in web/embed_test.go reimplements it deliberately — a test that imported
// the thing it checks would pass on a bug in it. The "any script that wants to check
// freshness" this was exported for was never written; `knip` said so.
function sourceHash(root) {
  const files = [
    ...walk(join(root, 'src')),
    join(root, 'index.html'),
    join(root, 'vite.config.js'),
    join(root, 'package-lock.json'),
  ].sort()
  const h = createHash('sha256')
  for (const f of files) {
    // The path is hashed as well as the bytes: renaming a component changes the build.
    h.update(relative(root, f).replaceAll('\\', '/'))
    h.update('\0')
    h.update(readFileSync(f))
    h.update('\0')
  }
  return h.digest('hex').slice(0, 32)
}

export function stamp() {
  let root
  return {
    name: 'mega-docs-stamp',
    configResolved(config) {
      root = config.root
    },
    // writeBundle rather than closeBundle: the file has to land in the output directory
    // that Vite has just finished emptying and filling.
    writeBundle(options) {
      const pkg = JSON.parse(readFileSync(join(root, 'package.json'), 'utf8'))
      writeFileSync(
        join(options.dir, 'build.json'),
        `${JSON.stringify({
          _comment:
            'Generated by web/ui/scripts/stamp.js — do not edit. `sources` is a hash of '
            + 'web/ui/src, index.html, vite.config.js and package-lock.json. '
            + 'TestBuiltUIMatchesItsSources fails when it no longer matches, which is how '
            + 'a committed bundle cannot go stale. Rebuild with `make ui`.',
          sources: sourceHash(root),
          vue: pkg.dependencies.vue,
          nes: pkg.dependencies['8bit-nes'],
        }, null, 2)}\n`,
      )
    },
  }
}
