#!/usr/bin/env bash
# Cut a release: generate web/release.json from git, commit it, then tag that commit.
#
# The order matters and is the whole trick. release.json has to be *in* the tagged commit,
# or `git describe` on what is deployed reads `v0.13.0-1-g…` forever — one commit past its
# own tag, because the file that names the tag landed after it. So: write, commit, then tag.
#
# Why generated at all, when the deploy already reports a commit: a commit answers "which
# bytes are running", and a reader asking "what changed?" cannot get there from a sha. The
# notes are read out of `git log`, never written by hand — changelog/README.md is explicit
# that the git log *is* the release notes, so a second prose copy would be a second truth
# with a delay on it.
#
# And the number is not bumped in a file anybody has to remember: the annotated tag is the
# only input. Forget to cut one and the badge falls back to `@<commit>` — still true, which
# is what the VERSION-file idea this replaces could not manage.
set -euo pipefail

cd "$(git rev-parse --show-toplevel)"

V="${V:-}"
[ -n "$V" ] || { echo "usage: make release V=v0.13.0" >&2; exit 2; }
case "$V" in
  v[0-9]*.[0-9]*.[0-9]*) ;;
  *) echo "release: V must look like v0.13.0, got '$V'" >&2; exit 2 ;;
esac

git rev-parse -q --verify "refs/tags/$V" >/dev/null &&
  { echo "release: tag $V already exists" >&2; exit 1; }
git diff --quiet && git diff --cached --quiet ||
  { echo "release: working tree is dirty — commit or stash first" >&2; git status --short; exit 1; }

# The previous tag bounds the log. With none, take the whole history: a first release is
# every commit, not an empty list.
PREV="$(git describe --tags --abbrev=0 2>/dev/null || true)"
RANGE="${PREV:+$PREV..}HEAD"
DATE="$(git log -1 --format=%cs)"

# Conventional-Commit subjects become {kind, scope, subject}; anything else lands under
# "other" with its subject intact rather than being dropped — a release that silently omits
# commits is worse than one with an untidy line in it.
NOTES="$(git log --no-merges --format='%h%x1f%s' "$RANGE" | awk -F'\037' '
  function esc(s) { gsub(/\\/, "\\\\", s); gsub(/"/, "\\\"", s); gsub(/\t/, " ", s); return s }
  {
    sha = $1; subj = $2; kind = "other"; scope = ""
    if (match(subj, /^[a-z]+(\([^)]+\))?!?: /)) {
      head = substr(subj, 1, RLENGTH - 2)
      subj = substr(subj, RLENGTH + 1)
      sub(/!$/, "", head)
      if (match(head, /\(/)) {
        kind  = substr(head, 1, index(head, "(") - 1)
        scope = substr(head, index(head, "(") + 1, length(head) - index(head, "(") - 1)
      } else kind = head
    }
    printf "%s{\"kind\":\"%s\",\"scope\":\"%s\",\"subject\":\"%s\",\"commit\":\"%s\"}",
      (NR > 1 ? ",\n    " : ""), esc(kind), esc(scope), esc(subj), esc(sha)
  }')"

cat > web/release.json <<JSON
{
  "_comment": "Generated by scripts/release.sh via \`make release\` — do not edit. The tag is the only input; the notes are read out of git log. TestReleaseNotesAreGenerated fails on a hand-written one.",
  "version": "$V",
  "date": "$DATE",
  "previous": "${PREV:-}",
  "notes": [
    $NOTES
  ]
}
JSON

git add web/release.json
git commit --quiet -m "release $V"
git tag -a "$V" -m "$V"
echo "  tagged $V at $(git rev-parse --short HEAD) — $(git log --no-merges --oneline "$RANGE" | wc -l | tr -d ' ') commits since ${PREV:-the beginning}"
echo "  push it:  git push origin main --follow-tags"
