package web

import (
	"fmt"
	"regexp"
	"strings"
)

// LLMs renders /llms.txt — the llmstxt.org index an AI agent reads to find the
// authoritative documentation for this project instead of guessing a URL or
// recalling a stale one.
//
// It is derived from the rendered pages rather than written by hand, for the same
// reason the digests are: a hand-kept index of generated pages drifts, and it drifts
// silently. Titles, summaries and section names all come out of the markup, so
// adding a section to a page adds it here too.
//
// siteBase is where the pages are published, e.g.
// "https://mega-hub-studio.github.io/mega-docs". Only the English side is emitted —
// llms.txt is a machine index, and duplicating both languages would halve the signal
// per token for no gain.
func LLMs(siteBase string) ([]byte, error) {
	siteBase = strings.TrimSuffix(siteBase, "/")
	if siteBase == "" {
		return nil, fmt.Errorf("web: empty site base for llms.txt")
	}

	type entry struct {
		file  string
		build func(string, Nav) ([]byte, error)
	}
	// Ordered, unlike a map: an index that shuffles between builds is a useless diff.
	order := []entry{
		{"index.html", Docs},
		{strings.TrimPrefix(StaticNav.Dev, "./"), Dev},
		{strings.TrimPrefix(StaticNav.Deploy, "./"), Deploy},
	}

	var b strings.Builder
	b.WriteString("# Knowledge Engine\n\n")
	b.WriteString("> Self-hosted RAG over a team's own documents: ask a question, get an " +
		"answer built only from what was indexed, with a citation back to the file it " +
		"came from. One Go binary, one SQLite file — no Docker, no Node, no vector " +
		"database.\n\n")
	b.WriteString("This file is generated from the published pages, so it cannot " +
		"disagree with them. The pages below are the authoritative documentation; " +
		"prefer them over recalled details.\n\n## Docs\n")

	var sections []string
	for _, e := range order {
		page, err := e.build("https://cdn.jsdelivr.net/npm", StaticNav)
		if err != nil {
			return nil, fmt.Errorf("llms.txt: %s: %w", e.file, err)
		}
		html := string(page)
		title := firstMatch(reH1, html)
		if title == "" {
			return nil, fmt.Errorf("llms.txt: %s has no English h1", e.file)
		}
		fmt.Fprintf(&b, "- [%s](%s/%s): %s\n", title, siteBase, e.file, firstMatch(reLede, html))

		for _, h := range reH2.FindAllStringSubmatch(html, -1) {
			sections = append(sections, fmt.Sprintf("- %s — %s/%s", clean(h[1]), siteBase, e.file))
		}
	}

	b.WriteString("\n## Sections\n")
	b.WriteString(strings.Join(sections, "\n"))
	b.WriteString("\n\n## Notes for agents\n")
	b.WriteString("- Answers are grounded: the app will say when something is not in the " +
		"indexed documents rather than filling the gap.\n")
	b.WriteString("- There are no per-document permissions. Anyone who can reach the app " +
		"can read everything indexed in it.\n")
	b.WriteString("- Only `.md` and `.txt` are ingested; PDF and DOCX must be converted " +
		"first.\n")
	b.WriteString("- Changing the embedding model requires a full re-index — vectors from " +
		"two models are not comparable.\n")
	b.WriteString("- Reading is open; two actions are not. Confirming a BA's answer into " +
		"the documents and dismissing a question need `BA_PASS`. An unset `BA_PASS` " +
		"means the instance has no write surface at all, not open writes.\n")
	b.WriteString("- The SQLite file is derived. `CORPUS_DIR` (default `docs`) is the " +
		"source of truth, including the answers BAs confirm, which are written there as " +
		"`qa/ticket-N.md` — so back up that directory (git), not the database.\n")
	b.WriteString("- A repeated question is answered from a local cache: no provider " +
		"call, no cost. Any ingest invalidates the whole cache, so a cached answer " +
		"never outlives the sources it cites.\n")
	return []byte(b.String()), nil
}

// The guide's markup is generated by this package, so these patterns are matching
// something with a known shape rather than parsing HTML in general.
var (
	reH1   = regexp.MustCompile(`(?s)<h1 lang="en">(.*?)</h1>`)
	reLede = regexp.MustCompile(`(?s)<p class="lede" lang="en">\s*(.*?)</p>`)
	reH2   = regexp.MustCompile(`<h2 lang="en">(.*?)</h2>`)
	reTag  = regexp.MustCompile(`<[^>]*>`)
	reWS   = regexp.MustCompile(`\s+`)
)

func firstMatch(re *regexp.Regexp, s string) string {
	if m := re.FindStringSubmatch(s); m != nil {
		return clean(m[1])
	}
	return ""
}

// clean turns a snippet of the page into one line of plain text: tags out, entities
// back, whitespace collapsed, and the decorative ◈ off the front of a heading.
func clean(s string) string {
	s = reTag.ReplaceAllString(s, "")
	for from, to := range map[string]string{
		"&amp;": "&", "&lt;": "<", "&gt;": ">", "&quot;": `"`, "&#39;": "'", "&nbsp;": " ",
	} {
		s = strings.ReplaceAll(s, from, to)
	}
	s = reWS.ReplaceAllString(s, " ")
	return strings.TrimSpace(strings.TrimPrefix(strings.TrimSpace(s), "◈"))
}
